#!/bin/csh -f

##########################################################################################
# Version: J-2014.09-SP2 (January 12, 2015)
# Copyright (C) 2010-2015 Synopsys, Inc. All rights reserved.
##########################################################################################
# This csh file is for two purposes:
# 1.Exit if perl path is not found
# 2.Exit if perl version is wrong and causing errors
############################################################################

echo "*ICC DP-RM: Looking for Perl path /usr/bin/perl"
set perl_path = /usr/bin/perl

   set found_Perl = 0
   if ( -e $perl_path ) then
	echo  "*ICC DP-RM: $perl_path found"
	set found_Perl = 1
   endif
   if ($found_Perl == 0) then
	echo "*ICC DP-RM: $perl_path not found!"
        echo "*ICC DP-RM: Exiting without running perl script."
        echo "*ICC DP-RM: Please update first line of ../../scripts_block/rm_icc_dp_scripts/gen_explore_table.pl with correct Perl path."
	exit
   endif

#############################################################################

echo ""

../../scripts_block/rm_icc_dp_scripts/gen_explore_table.pl -i $argv[1] -o ./ -f $argv[2]   

echo ""

echo "*ICC DP-RM: gen_explore_table.pl program has completed."
echo ""

